packages:
  - .
  - vendor/discord.js-selfbot-v13
  - vendor/Discord-video-stream

onlyBuiltDependencies:
  - '@discordjs/opus'
  - '@lng2004/node-datachannel'
  - better-sqlite3
  - esbuild
  - node-av
  - sharp
  - zeromq
