/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AnalysisRouteRouteImport } from './routes/analysis/route'
import { Route as ChannelsRouteRouteImport } from './routes/channels/route'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as GlossaryRouteRouteImport } from './routes/glossary/route'
import { Route as MessagesRouteRouteImport } from './routes/messages/route'
import { Route as ModerationRouteRouteImport } from './routes/moderation/route'
import { Route as UsersRouteRouteImport } from './routes/users/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRouteRoute = AnalysisRouteRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ChannelsRouteRoute = ChannelsRouteRouteImport.update({
  id: '/channels',
  path: '/channels',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRouteRoute = GlossaryRouteRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRouteRoute = MessagesRouteRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRouteRoute = ModerationRouteRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRouteRoute = UsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteRoute
  '/channels': typeof ChannelsRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/glossary': typeof GlossaryRouteRoute
  '/messages': typeof MessagesRouteRoute
  '/moderation': typeof ModerationRouteRoute
  '/users': typeof UsersRouteRoute
  '/$': typeof SplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteRoute
  '/channels': typeof ChannelsRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/glossary': typeof GlossaryRouteRoute
  '/messages': typeof MessagesRouteRoute
  '/moderation': typeof ModerationRouteRoute
  '/users': typeof UsersRouteRoute
  '/$': typeof SplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analysis': typeof AnalysisRouteRoute
  '/channels': typeof ChannelsRouteRoute
  '/dashboard': typeof DashboardRouteRoute
  '/glossary': typeof GlossaryRouteRoute
  '/messages': typeof MessagesRouteRoute
  '/moderation': typeof ModerationRouteRoute
  '/users': typeof UsersRouteRoute
  '/$': typeof SplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/channels'
    | '/dashboard'
    | '/glossary'
    | '/messages'
    | '/moderation'
    | '/users'
    | '/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/channels'
    | '/dashboard'
    | '/glossary'
    | '/messages'
    | '/moderation'
    | '/users'
    | '/$'
  id:
    | '__root__'
    | '/'
    | '/analysis'
    | '/channels'
    | '/dashboard'
    | '/glossary'
    | '/messages'
    | '/moderation'
    | '/users'
    | '/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalysisRouteRoute: typeof AnalysisRouteRoute
  ChannelsRouteRoute: typeof ChannelsRouteRoute
  DashboardRouteRoute: typeof DashboardRouteRoute
  GlossaryRouteRoute: typeof GlossaryRouteRoute
  MessagesRouteRoute: typeof MessagesRouteRoute
  ModerationRouteRoute: typeof ModerationRouteRoute
  UsersRouteRoute: typeof UsersRouteRoute
  SplatRoute: typeof SplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/channels': {
      id: '/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof ChannelsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalysisRouteRoute: AnalysisRouteRoute,
  ChannelsRouteRoute: ChannelsRouteRoute,
  DashboardRouteRoute: DashboardRouteRoute,
  GlossaryRouteRoute: GlossaryRouteRoute,
  MessagesRouteRoute: MessagesRouteRoute,
  ModerationRouteRoute: ModerationRouteRoute,
  UsersRouteRoute: UsersRouteRoute,
  SplatRoute: SplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
