/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedSplatRouteImport } from './routes/_authenticated/$'
import { Route as AuthenticatedAnalysisRouteRouteImport } from './routes/_authenticated/analysis/route'
import { Route as AuthenticatedChannelsRouteRouteImport } from './routes/_authenticated/channels/route'
import { Route as AuthenticatedDashboardRouteRouteImport } from './routes/_authenticated/dashboard/route'
import { Route as AuthenticatedGlossaryRouteRouteImport } from './routes/_authenticated/glossary/route'
import { Route as AuthenticatedMessagesRouteRouteImport } from './routes/_authenticated/messages/route'
import { Route as AuthenticatedModerationRouteRouteImport } from './routes/_authenticated/moderation/route'
import { Route as AuthenticatedUsersRouteRouteImport } from './routes/_authenticated/users/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSplatRoute = AuthenticatedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalysisRouteRoute =
  AuthenticatedAnalysisRouteRouteImport.update({
    id: '/analysis',
    path: '/analysis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChannelsRouteRoute =
  AuthenticatedChannelsRouteRouteImport.update({
    id: '/channels',
    path: '/channels',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRouteRoute =
  AuthenticatedDashboardRouteRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGlossaryRouteRoute =
  AuthenticatedGlossaryRouteRouteImport.update({
    id: '/glossary',
    path: '/glossary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesRouteRoute =
  AuthenticatedMessagesRouteRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedModerationRouteRoute =
  AuthenticatedModerationRouteRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsersRouteRoute = AuthenticatedUsersRouteRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analysis': typeof AuthenticatedAnalysisRouteRoute
  '/channels': typeof AuthenticatedChannelsRouteRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/glossary': typeof AuthenticatedGlossaryRouteRoute
  '/messages': typeof AuthenticatedMessagesRouteRoute
  '/moderation': typeof AuthenticatedModerationRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/$': typeof AuthenticatedSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analysis': typeof AuthenticatedAnalysisRouteRoute
  '/channels': typeof AuthenticatedChannelsRouteRoute
  '/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/glossary': typeof AuthenticatedGlossaryRouteRoute
  '/messages': typeof AuthenticatedMessagesRouteRoute
  '/moderation': typeof AuthenticatedModerationRouteRoute
  '/users': typeof AuthenticatedUsersRouteRoute
  '/$': typeof AuthenticatedSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/analysis': typeof AuthenticatedAnalysisRouteRoute
  '/_authenticated/channels': typeof AuthenticatedChannelsRouteRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteRoute
  '/_authenticated/glossary': typeof AuthenticatedGlossaryRouteRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRouteRoute
  '/_authenticated/moderation': typeof AuthenticatedModerationRouteRoute
  '/_authenticated/users': typeof AuthenticatedUsersRouteRoute
  '/_authenticated/$': typeof AuthenticatedSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analysis'
    | '/channels'
    | '/dashboard'
    | '/glossary'
    | '/messages'
    | '/moderation'
    | '/users'
    | '/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analysis'
    | '/channels'
    | '/dashboard'
    | '/glossary'
    | '/messages'
    | '/moderation'
    | '/users'
    | '/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/analysis'
    | '/_authenticated/channels'
    | '/_authenticated/dashboard'
    | '/_authenticated/glossary'
    | '/_authenticated/messages'
    | '/_authenticated/moderation'
    | '/_authenticated/users'
    | '/_authenticated/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$': {
      id: '/_authenticated/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AuthenticatedSplatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analysis': {
      id: '/_authenticated/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AuthenticatedAnalysisRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/channels': {
      id: '/_authenticated/channels'
      path: '/channels'
      fullPath: '/channels'
      preLoaderRoute: typeof AuthenticatedChannelsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/glossary': {
      id: '/_authenticated/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof AuthenticatedGlossaryRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/moderation': {
      id: '/_authenticated/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AuthenticatedModerationRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAnalysisRouteRoute: typeof AuthenticatedAnalysisRouteRoute
  AuthenticatedChannelsRouteRoute: typeof AuthenticatedChannelsRouteRoute
  AuthenticatedDashboardRouteRoute: typeof AuthenticatedDashboardRouteRoute
  AuthenticatedGlossaryRouteRoute: typeof AuthenticatedGlossaryRouteRoute
  AuthenticatedMessagesRouteRoute: typeof AuthenticatedMessagesRouteRoute
  AuthenticatedModerationRouteRoute: typeof AuthenticatedModerationRouteRoute
  AuthenticatedUsersRouteRoute: typeof AuthenticatedUsersRouteRoute
  AuthenticatedSplatRoute: typeof AuthenticatedSplatRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAnalysisRouteRoute: AuthenticatedAnalysisRouteRoute,
  AuthenticatedChannelsRouteRoute: AuthenticatedChannelsRouteRoute,
  AuthenticatedDashboardRouteRoute: AuthenticatedDashboardRouteRoute,
  AuthenticatedGlossaryRouteRoute: AuthenticatedGlossaryRouteRoute,
  AuthenticatedMessagesRouteRoute: AuthenticatedMessagesRouteRoute,
  AuthenticatedModerationRouteRoute: AuthenticatedModerationRouteRoute,
  AuthenticatedUsersRouteRoute: AuthenticatedUsersRouteRoute,
  AuthenticatedSplatRoute: AuthenticatedSplatRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
